name: Update GitHub Trending Data

on:
  schedule:
    # 每天凌晨2点运行（UTC时间）
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-trending:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml
        
    - name: Run trending scraper
      run: |
        python scripts/fetch_trending.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add trending-data.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update trending data [skip ci]"
        git push 